"""Add PurchaseListItem model

Revision ID: b5266c1632cb
Revises: e6b42bdcf58b
Create Date: 2024-07-08 13:02:34.551283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5266c1632cb'
down_revision = 'e6b42bdcf58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_list_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_list_item_name'), ['name'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('purchase_list_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_list_item_name'))

    op.drop_table('purchase_list_item')
    # ### end Alembic commands ###
