"""Add frequency to Item model

Revision ID: e6b42bdcf58b
Revises: 2e9ba038e8f0
Create Date: 2024-07-06 22:30:51.524294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b42bdcf58b'
down_revision = '2e9ba038e8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
